### ISSUE TITLE
Dynamically disabling/enabling button based on form data validity.

### ISSUE THREAD

**Issue by yrammos** [53js/react-jsonschema-form-validation#2]
I am trying to wire the submit button the the `Form` component's `valid` state. In other words, the goal is to keep the button disabled until the form satisfies all validity constraints.

My current implementation is based on React references and, as expected, works unsatisfactorily due to the asynchronous nature of the process. There is no guarantee that the `valid` state of the `Form` component is updated by the time `setState` is run in the parent component:

```jsx
this.FormRef = React.createRef(null);

handleChange = (data) => {
     this.setState({
        formData: data,
        success: false,
        invalid: !this.FormRef.current.state.valid
    })
}
...
<Form
   ref={this.FormRef}
   …
>
…
</Form>
```

ReactJS is still somewhat out of my depth, but I wonder whether the `Form` component could be tweaked to expose its `valid` state more reliably and painlessly—for instance by passing `valid` as a prop to the onChange callback, or including it in form data, or by not triggering the `onChange` handler until the state has been updated.

Thanks for your help and for a fantastic library.

**Comment by yrammos** [comment]
In retrospect, this seems to work:

```jsx
this.FormRef = React.createRef(null);

handleChange = (data) => {
	this.setState({
		formData: data,
		success: false,
	}, () => {
		setTimeout(() => {
			this.setState({
				invalid: !this.FormRef.current.state.valid
			}, () => (console.log(`=== New state: ${JSON.stringify(this.state)}`)))
		}, 500)
	})
}
…
<Form
   ref={this.FormRef}
   …
>
…
</Form>
```

Removing the nested `setTimeout` breaks the handler, so a timing issue might be at work.

**Comment by hugomallet** [comment]
**Making a submit button which is disabled when form is invalid** 
I have updated the docs. You will find a new example which uses the form context using react hooks : [demo](https://53js.github.io/react-jsonschema-form-validation/#/examples/context-form) / [source](https://github.com/53js/react-jsonschema-form-validation/tree/master/src/demo/context)
(the same example would also work using the context api instead of hooks)

**About the state of the form in the onChange handler**
Actually the data is validated when the prop data of the Form component changes. So, in your example, this happen after calling  
```js
this.setState({
		formData: data,
		success: false,
	}
```  
This why you need the setTimeout (the handleChange event happens before the data is validated).

**Comment by yrammos** [comment]
The model works excellently and etches this fundamental React pattern to my memory. Thank you for a quick and expert reply.
